const level5 = {
  theme: "YELLOW",
  tilesHeight: 13,
  tilesWidth: 13,
  tiles: [
    { x: 0, y: 0, frameCoordinate: "1x1" },
    { x: 1, y: 0, frameCoordinate: "1x1" },
    { x: 2, y: 0, frameCoordinate: "1x1" },
    { x: 3, y: 0, frameCoordinate: "1x1" },
    { x: 4, y: 0, frameCoordinate: "1x1" },
    { x: 5, y: 0, frameCoordinate: "1x1" },
    { x: 6, y: 0, frameCoordinate: "1x1" },
    { x: 7, y: 0, frameCoordinate: "1x1" },
    { x: 8, y: 0, frameCoordinate: "1x1" },
    { x: 9, y: 0, frameCoordinate: "1x1" },
    { x: 10, y: 0, frameCoordinate: "1x1" },
    { x: 11, y: 0, frameCoordinate: "1x1" },
    { x: 12, y: 0, frameCoordinate: "1x1" },
    { x: 0, y: 1, frameCoordinate: "1x1" },
    { x: 1, y: 1, frameCoordinate: "1x1" },
    { x: 2, y: 1, frameCoordinate: "1x1" },
    { x: 3, y: 1, frameCoordinate: "1x1" },
    { x: 4, y: 1, frameCoordinate: "1x1" },
    { x: 5, y: 1, frameCoordinate: "1x1" },
    { x: 6, y: 1, frameCoordinate: "1x1" },
    { x: 7, y: 1, frameCoordinate: "1x1" },
    { x: 8, y: 1, frameCoordinate: "1x1" },
    { x: 9, y: 1, frameCoordinate: "1x1" },
    { x: 10, y: 1, frameCoordinate: "1x1" },
    { x: 11, y: 1, frameCoordinate: "1x1" },
    { x: 12, y: 1, frameCoordinate: "1x1" },
    { x: 0, y: 2, frameCoordinate: "1x1" },
    { x: 1, y: 2, frameCoordinate: "1x1" },
    { x: 2, y: 2, frameCoordinate: "1x1" },
    { x: 3, y: 2, frameCoordinate: "1x1" },
    { x: 4, y: 2, frameCoordinate: "1x1" },
    { x: 5, y: 2, frameCoordinate: "1x1" },
    { x: 6, y: 2, frameCoordinate: "1x1" },
    { x: 7, y: 2, frameCoordinate: "1x1" },
    { x: 8, y: 2, frameCoordinate: "1x1" },
    { x: 9, y: 2, frameCoordinate: "1x1" },
    { x: 10, y: 2, frameCoordinate: "1x1" },
    { x: 11, y: 2, frameCoordinate: "1x1" },
    { x: 12, y: 2, frameCoordinate: "1x1" },
    { x: 0, y: 3, frameCoordinate: "1x1" },
    { x: 1, y: 3, frameCoordinate: "1x1" },
    { x: 2, y: 3, frameCoordinate: "1x1" },
    { x: 3, y: 3, frameCoordinate: "1x1" },
    { x: 4, y: 3, frameCoordinate: "1x1" },
    { x: 5, y: 3, frameCoordinate: "1x1" },
    { x: 6, y: 3, frameCoordinate: "1x1" },
    { x: 7, y: 3, frameCoordinate: "1x1" },
    { x: 8, y: 3, frameCoordinate: "1x1" },
    { x: 9, y: 3, frameCoordinate: "1x1" },
    { x: 10, y: 3, frameCoordinate: "1x1" },
    { x: 11, y: 3, frameCoordinate: "1x1" },
    { x: 12, y: 3, frameCoordinate: "1x1" },
    { x: 0, y: 4, frameCoordinate: "1x1" },
    { x: 1, y: 4, frameCoordinate: "1x1" },
    { x: 2, y: 4, frameCoordinate: "1x1" },
    { x: 3, y: 4, frameCoordinate: "1x1" },
    { x: 4, y: 4, frameCoordinate: "1x1" },
    { x: 5, y: 4, frameCoordinate: "1x1" },
    { x: 6, y: 4, frameCoordinate: "1x1" },
    { x: 7, y: 4, frameCoordinate: "1x1" },
    { x: 8, y: 4, frameCoordinate: "1x1" },
    { x: 9, y: 4, frameCoordinate: "1x1" },
    { x: 10, y: 4, frameCoordinate: "1x1" },
    { x: 11, y: 4, frameCoordinate: "1x1" },
    { x: 12, y: 4, frameCoordinate: "1x1" },
    { x: 0, y: 5, frameCoordinate: "1x1" },
    { x: 1, y: 5, frameCoordinate: "1x1" },
    { x: 2, y: 5, frameCoordinate: "1x1" },
    { x: 3, y: 5, frameCoordinate: "1x1" },
    { x: 4, y: 5, frameCoordinate: "1x1" },
    { x: 5, y: 5, frameCoordinate: "1x1" },
    { x: 6, y: 5, frameCoordinate: "1x1" },
    { x: 7, y: 5, frameCoordinate: "1x1" },
    { x: 8, y: 5, frameCoordinate: "1x1" },
    { x: 9, y: 5, frameCoordinate: "1x1" },
    { x: 10, y: 5, frameCoordinate: "1x1" },
    { x: 11, y: 5, frameCoordinate: "1x1" },
    { x: 12, y: 5, frameCoordinate: "1x1" },
    { x: 0, y: 6, frameCoordinate: "1x1" },
    { x: 1, y: 6, frameCoordinate: "1x1" },
    { x: 2, y: 6, frameCoordinate: "1x1" },
    { x: 3, y: 6, frameCoordinate: "1x1" },
    { x: 4, y: 6, frameCoordinate: "1x1" },
    { x: 5, y: 6, frameCoordinate: "1x1" },
    { x: 6, y: 6, frameCoordinate: "1x1" },
    { x: 7, y: 6, frameCoordinate: "1x1" },
    { x: 8, y: 6, frameCoordinate: "1x1" },
    { x: 9, y: 6, frameCoordinate: "1x1" },
    { x: 10, y: 6, frameCoordinate: "1x1" },
    { x: 11, y: 6, frameCoordinate: "1x1" },
    { x: 12, y: 6, frameCoordinate: "1x1" },
    { x: 0, y: 7, frameCoordinate: "1x1" },
    { x: 1, y: 7, frameCoordinate: "1x1" },
    { x: 2, y: 7, frameCoordinate: "1x1" },
    { x: 3, y: 7, frameCoordinate: "1x1" },
    { x: 4, y: 7, frameCoordinate: "1x1" },
    { x: 5, y: 7, frameCoordinate: "1x1" },
    { x: 6, y: 7, frameCoordinate: "1x1" },
    { x: 7, y: 7, frameCoordinate: "1x1" },
    { x: 8, y: 7, frameCoordinate: "1x1" },
    { x: 9, y: 7, frameCoordinate: "1x1" },
    { x: 10, y: 7, frameCoordinate: "1x1" },
    { x: 11, y: 7, frameCoordinate: "1x1" },
    { x: 12, y: 7, frameCoordinate: "1x1" },
    { x: 0, y: 8, frameCoordinate: "1x1" },
    { x: 1, y: 8, frameCoordinate: "1x1" },
    { x: 2, y: 8, frameCoordinate: "1x1" },
    { x: 3, y: 8, frameCoordinate: "1x1" },
    { x: 4, y: 8, frameCoordinate: "1x1" },
    { x: 5, y: 8, frameCoordinate: "1x1" },
    { x: 6, y: 8, frameCoordinate: "1x1" },
    { x: 7, y: 8, frameCoordinate: "1x1" },
    { x: 8, y: 8, frameCoordinate: "1x1" },
    { x: 9, y: 8, frameCoordinate: "1x1" },
    { x: 10, y: 8, frameCoordinate: "1x1" },
    { x: 11, y: 8, frameCoordinate: "1x1" },
    { x: 12, y: 8, frameCoordinate: "1x1" },
    { x: 0, y: 9, frameCoordinate: "1x1" },
    { x: 1, y: 9, frameCoordinate: "1x1" },
    { x: 2, y: 9, frameCoordinate: "1x1" },
    { x: 3, y: 9, frameCoordinate: "1x1" },
    { x: 4, y: 9, frameCoordinate: "1x1" },
    { x: 5, y: 9, frameCoordinate: "1x1" },
    { x: 6, y: 9, frameCoordinate: "1x1" },
    { x: 7, y: 9, frameCoordinate: "1x1" },
    { x: 8, y: 9, frameCoordinate: "1x1" },
    { x: 9, y: 9, frameCoordinate: "1x1" },
    { x: 10, y: 9, frameCoordinate: "1x1" },
    { x: 11, y: 9, frameCoordinate: "1x1" },
    { x: 12, y: 9, frameCoordinate: "1x1" },
    { x: 0, y: 10, frameCoordinate: "1x1" },
    { x: 1, y: 10, frameCoordinate: "1x1" },
    { x: 2, y: 10, frameCoordinate: "1x1" },
    { x: 3, y: 10, frameCoordinate: "1x1" },
    { x: 4, y: 10, frameCoordinate: "1x1" },
    { x: 5, y: 10, frameCoordinate: "1x1" },
    { x: 6, y: 10, frameCoordinate: "1x1" },
    { x: 7, y: 10, frameCoordinate: "1x1" },
    { x: 8, y: 10, frameCoordinate: "1x1" },
    { x: 9, y: 10, frameCoordinate: "1x1" },
    { x: 10, y: 10, frameCoordinate: "1x1" },
    { x: 11, y: 10, frameCoordinate: "1x1" },
    { x: 12, y: 10, frameCoordinate: "1x1" },
    { x: 0, y: 11, frameCoordinate: "1x1" },
    { x: 1, y: 11, frameCoordinate: "1x1" },
    { x: 2, y: 11, frameCoordinate: "1x1" },
    { x: 3, y: 11, frameCoordinate: "1x1" },
    { x: 4, y: 11, frameCoordinate: "1x1" },
    { x: 5, y: 11, frameCoordinate: "1x1" },
    { x: 6, y: 11, frameCoordinate: "1x1" },
    { x: 7, y: 11, frameCoordinate: "1x1" },
    { x: 8, y: 11, frameCoordinate: "1x1" },
    { x: 9, y: 11, frameCoordinate: "1x1" },
    { x: 10, y: 11, frameCoordinate: "1x1" },
    { x: 11, y: 11, frameCoordinate: "1x1" },
    { x: 12, y: 11, frameCoordinate: "1x1" },
    { x: 0, y: 12, frameCoordinate: null },
    { x: 1, y: 12, frameCoordinate: "1x1" },
    { x: 2, y: 12, frameCoordinate: "1x1" },
    { x: 3, y: 12, frameCoordinate: "1x1" },
    { x: 4, y: 12, frameCoordinate: "1x1" },
    { x: 5, y: 12, frameCoordinate: "1x1" },
    { x: 6, y: 12, frameCoordinate: "1x1" },
    { x: 7, y: 12, frameCoordinate: "1x1" },
    { x: 8, y: 12, frameCoordinate: "1x1" },
    { x: 9, y: 12, frameCoordinate: "1x1" },
    { x: 10, y: 12, frameCoordinate: "1x1" },
    { x: 11, y: 12, frameCoordinate: "1x1" },
    { x: 12, y: 12, frameCoordinate: null },
  ],
  placements: [
    { type: "HERO", x: 2, y: 2 },
    { type: "WALL", x: 4, y: 1 },
    { type: "WALL", x: 4, y: 3 },
    { type: "WALL", x: 4, y: 4 },
    { type: "WALL", x: 4, y: 5 },
    { type: "WALL", x: 3, y: 4 },
    { type: "WALL", x: 5, y: 4 },
    { type: "WALL", x: 4, y: 8 },
    { type: "WALL", x: 4, y: 7 },
    { type: "WALL", x: 3, y: 8 },
    { type: "WALL", x: 5, y: 8 },
    { type: "WALL", x: 1, y: 8 },
    { type: "WALL", x: 4, y: 9 },
    { type: "WALL", x: 4, y: 11 },
    { type: "WALL", x: 7, y: 4 },
    { type: "WALL", x: 8, y: 4 },
    { type: "WALL", x: 8, y: 3 },
    { type: "WALL", x: 9, y: 4 },
    { type: "WALL", x: 8, y: 5 },
    { type: "WALL", x: 8, y: 1 },
    { type: "WALL", x: 11, y: 4 },
    { type: "WALL", x: 8, y: 7 },
    { type: "WALL", x: 8, y: 8 },
    { type: "WALL", x: 9, y: 8 },
    { type: "WALL", x: 7, y: 8 },
    { type: "WALL", x: 8, y: 9 },
    { type: "WALL", x: 11, y: 8 },
    { type: "WALL", x: 8, y: 11 },
    { type: "WATER", x: 5, y: 1 },
    { type: "WATER", x: 6, y: 1 },
    { type: "WATER", x: 7, y: 1 },
    { type: "WATER", x: 5, y: 3 },
    { type: "WATER", x: 6, y: 3 },
    { type: "WATER", x: 7, y: 3 },
    { type: "WATER", x: 9, y: 1 },
    { type: "WATER", x: 10, y: 1 },
    { type: "WATER", x: 11, y: 1 },
    { type: "WATER", x: 11, y: 2 },
    { type: "WATER", x: 11, y: 3 },
    { type: "WATER", x: 10, y: 3 },
    { type: "WATER", x: 9, y: 3 },
    { type: "WATER", x: 9, y: 5 },
    { type: "WATER", x: 10, y: 5 },
    { type: "WATER", x: 11, y: 5 },
    { type: "WATER", x: 11, y: 6 },
    { type: "WATER", x: 11, y: 7 },
    { type: "WATER", x: 10, y: 7 },
    { type: "WATER", x: 9, y: 7 },
    { type: "WATER", x: 9, y: 6 },
    { type: "WATER", x: 5, y: 5 },
    { type: "WATER", x: 7, y: 5 },
    { type: "WATER", x: 6, y: 7 },
    { type: "WATER", x: 5, y: 7 },
    { type: "WATER", x: 5, y: 6 },
    { type: "WATER", x: 7, y: 6 },
    { type: "WATER", x: 7, y: 7 },
    { type: "WATER", x: 1, y: 5 },
    { type: "WATER", x: 2, y: 5 },
    { type: "WATER", x: 3, y: 5 },
    { type: "WATER", x: 3, y: 6 },
    { type: "WATER", x: 3, y: 7 },
    { type: "WATER", x: 2, y: 7 },
    { type: "WATER", x: 1, y: 6 },
    { type: "WATER", x: 1, y: 7 },
    { type: "WATER", x: 2, y: 9 },
    { type: "WATER", x: 3, y: 9 },
    { type: "WATER", x: 3, y: 10 },
    { type: "WATER", x: 3, y: 11 },
    { type: "WATER", x: 2, y: 11 },
    { type: "WATER", x: 1, y: 10 },
    { type: "WATER", x: 1, y: 11 },
    { type: "WATER", x: 1, y: 9 },
    { type: "WATER", x: 5, y: 9 },
    { type: "WATER", x: 7, y: 9 },
    { type: "WATER", x: 7, y: 10 },
    { type: "WATER", x: 7, y: 11 },
    { type: "WATER", x: 6, y: 11 },
    { type: "WATER", x: 5, y: 11 },
    { type: "WATER", x: 5, y: 10 },
    { type: "WATER", x: 6, y: 10 },
    { type: "WATER", x: 6, y: 9 },
    { type: "WATER", x: 9, y: 9 },
    { type: "WATER", x: 10, y: 9 },
    { type: "WATER", x: 11, y: 9 },
    { type: "WATER", x: 11, y: 10 },
    { type: "WATER", x: 11, y: 11 },
    { type: "WATER", x: 10, y: 11 },
    { type: "WATER", x: 9, y: 11 },
    { type: "WATER", x: 9, y: 10 },
    { type: "WATER", x: 10, y: 10 },
    { type: "WATER", x: 10, y: 6 },
    { type: "WATER", x: 2, y: 6 },
    { type: "WATER", x: 2, y: 10 },
    { type: "GOAL", x: 6, y: 6 },
    { type: "WALL", x: 1, y: 4 },
    { type: "WATER", x: 6, y: 5 },
    { type: "THIEF", x: 8, y: 6 },
    { type: "THIEF", x: 4, y: 10 },
    { type: "THIEF", x: 4, y: 2 },
    { type: "SWITCH_DOOR", x: 2, y: 8 },
    { type: "SWITCH_DOOR", x: 6, y: 8 },
    { type: "SWITCH_DOOR", x: 10, y: 8 },
    { type: "SWITCH_DOOR", x: 10, y: 4 },
    { type: "SWITCH", x: 8, y: 10 },
    { type: "LOCK", x: 6, y: 4, color: "GREEN" },
    { type: "LOCK", x: 4, y: 6, color: "BLUE" },
    { type: "FLOUR", x: 2, y: 10 },
    { type: "KEY", x: 2, y: 6, color: "GREEN" },
    { type: "KEY", x: 10, y: 6, color: "BLUE" },
    { type: "SWITCH_DOOR", x: 2, y: 4 },
    { type: "WATER_PICKUP", x: 10, y: 2 },
    { type: "BOUND", x: 0, y: 0, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 2, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 1, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 3, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 4, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 5, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 6, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 7, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 8, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 10, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 9, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 11, direction: "LEFT" },
    { type: "BOUND", x: 1, y: 12, direction: "BOTTOM" },
    { type: "BOUND", x: 3, y: 12, direction: "BOTTOM" },
    { type: "BOUND", x: 2, y: 12, direction: "BOTTOM" },
    { type: "BOUND", x: 5, y: 12, direction: "BOTTOM" },
    { type: "BOUND", x: 4, y: 12, direction: "BOTTOM" },
    { type: "BOUND", x: 6, y: 12, direction: "BOTTOM" },
    { type: "BOUND", x: 7, y: 12, direction: "BOTTOM" },
    { type: "BOUND", x: 8, y: 12, direction: "BOTTOM" },
    { type: "BOUND", x: 9, y: 12, direction: "BOTTOM" },
    { type: "BOUND", x: 10, y: 12, direction: "BOTTOM" },
    { type: "BOUND", x: 11, y: 12, direction: "BOTTOM" },
    { type: "BOUND", x: 12, y: 11, direction: "RIGHT" },
    { type: "BOUND", x: 12, y: 10, direction: "RIGHT" },
    { type: "BOUND", x: 12, y: 9, direction: "RIGHT" },
    { type: "BOUND", x: 12, y: 8, direction: "RIGHT" },
    { type: "BOUND", x: 12, y: 7, direction: "RIGHT" },
    { type: "BOUND", x: 12, y: 5, direction: "RIGHT" },
    { type: "BOUND", x: 12, y: 6, direction: "RIGHT" },
    { type: "BOUND", x: 12, y: 4, direction: "RIGHT" },
    { type: "BOUND", x: 12, y: 3, direction: "RIGHT" },
    { type: "BOUND", x: 12, y: 1, direction: "RIGHT" },
    { type: "BOUND", x: 12, y: 2, direction: "RIGHT" },
    { type: "BOUND", x: 12, y: 0, direction: "RIGHT" },
    { type: "BOUND", x: 11, y: 0, direction: "TOP" },
    { type: "BOUND", x: 9, y: 0, direction: "TOP" },
    { type: "BOUND", x: 10, y: 0, direction: "TOP" },
    { type: "BOUND", x: 8, y: 0, direction: "TOP" },
    { type: "BOUND", x: 7, y: 0, direction: "TOP" },
    { type: "BOUND", x: 6, y: 0, direction: "TOP" },
    { type: "BOUND", x: 5, y: 0, direction: "TOP" },
    { type: "BOUND", x: 4, y: 0, direction: "TOP" },
    { type: "BOUND", x: 3, y: 0, direction: "TOP" },
    { type: "BOUND", x: 2, y: 0, direction: "TOP" },
    { type: "BOUND", x: 1, y: 0, direction: "TOP" },
  ],
};

export default level5;
