import { LevelThemes } from "@/constants/helpers";

const levelSample = {
  theme: LevelThemes.Gray,
  tilesHeight: 6,
  tilesWidth: 6,
  tiles: [
    { x: 0, y: 0, frameCoordinate: "13x1" },
    { x: 1, y: 0, frameCoordinate: "13x1" },
    { x: 2, y: 0, frameCoordinate: "13x1" },
    { x: 3, y: 0, frameCoordinate: "13x1" },
    { x: 4, y: 0, frameCoordinate: "13x1" },
    { x: 5, y: 0, frameCoordinate: "13x1" },
    { x: 0, y: 1, frameCoordinate: "13x1" },
    { x: 1, y: 1, frameCoordinate: "13x1" },
    { x: 2, y: 1, frameCoordinate: "13x1" },
    { x: 3, y: 1, frameCoordinate: "13x1" },
    { x: 4, y: 1, frameCoordinate: "13x1" },
    { x: 5, y: 1, frameCoordinate: "13x1" },
    { x: 0, y: 2, frameCoordinate: "13x1" },
    { x: 1, y: 2, frameCoordinate: "13x1" },
    { x: 2, y: 2, frameCoordinate: "13x1" },
    { x: 3, y: 2, frameCoordinate: "13x1" },
    { x: 4, y: 2, frameCoordinate: "13x1" },
    { x: 5, y: 2, frameCoordinate: "13x1" },
    { x: 0, y: 3, frameCoordinate: "13x1" },
    { x: 1, y: 3, frameCoordinate: "13x1" },
    { x: 2, y: 3, frameCoordinate: "13x1" },
    { x: 3, y: 3, frameCoordinate: "13x1" },
    { x: 4, y: 3, frameCoordinate: "13x1" },
    { x: 5, y: 3, frameCoordinate: "13x1" },
    { x: 0, y: 4, frameCoordinate: "13x1" },
    { x: 1, y: 4, frameCoordinate: "13x1" },
    { x: 2, y: 4, frameCoordinate: "13x1" },
    { x: 3, y: 4, frameCoordinate: "13x1" },
    { x: 4, y: 4, frameCoordinate: "13x1" },
    { x: 5, y: 4, frameCoordinate: "13x1" },
    { x: 0, y: 5, frameCoordinate: null },
    { x: 1, y: 5, frameCoordinate: "13x1" },
    { x: 2, y: 5, frameCoordinate: "13x1" },
    { x: 3, y: 5, frameCoordinate: "13x1" },
    { x: 4, y: 5, frameCoordinate: "13x1" },
    { x: 5, y: 5, frameCoordinate: null },
  ],
  placements: [
    { type: "HERO", x: 4, y: 2 },
    { type: "BOUND", x: 0, y: 0, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 1, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 3, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 2, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 4, direction: "LEFT" },
    { type: "BOUND", x: 5, y: 0, direction: "RIGHT" },
    { type: "BOUND", x: 5, y: 1, direction: "RIGHT" },
    { type: "BOUND", x: 5, y: 2, direction: "RIGHT" },
    { type: "BOUND", x: 5, y: 3, direction: "RIGHT" },
    { type: "BOUND", x: 5, y: 4, direction: "RIGHT" },
    { type: "BOUND", x: 4, y: 5, direction: "BOTTOM" },
    { type: "BOUND", x: 3, y: 5, direction: "BOTTOM" },
    { type: "BOUND", x: 2, y: 5, direction: "BOTTOM" },
    { type: "BOUND", x: 1, y: 5, direction: "BOTTOM" },
    { type: "BOUND", x: 1, y: 0, direction: "TOP" },
    { type: "BOUND", x: 2, y: 0, direction: "TOP" },
    { type: "BOUND", x: 3, y: 0, direction: "TOP" },
    { type: "BOUND", x: 4, y: 0, direction: "TOP" },
    { type: "LOCK", x: 2, y: 1, color: "BLUE" },
    { type: "KEY", x: 4, y: 2, color: "BLUE" },
    { type: "SWITCH", x: 4, y: 4 },
    { type: "SWITCH_DOOR", x: 2, y: 2 },
    { type: "WALL", x: 3, y: 1 },
    { type: "WALL", x: 3, y: 2 },
    { type: "WALL", x: 1, y: 2 },
    { type: "WALL", x: 1, y: 1 },
  ],
};

export default levelSample;
