import { ICE_CORNERS } from "@/constants/helpers";

const level1 = {
  theme: "BLUE",
  tilesHeight: 12,
  tilesWidth: 12,
  tiles: [
    { x: 0, y: 0, frameCoordinate: null },
    { x: 1, y: 0, frameCoordinate: "4x1" },
    { x: 2, y: 0, frameCoordinate: "4x1" },
    { x: 3, y: 0, frameCoordinate: "4x1" },
    { x: 4, y: 0, frameCoordinate: "4x1" },
    { x: 5, y: 0, frameCoordinate: "4x1" },
    { x: 6, y: 0, frameCoordinate: "4x1" },
    { x: 7, y: 0, frameCoordinate: "4x1" },
    { x: 8, y: 0, frameCoordinate: "4x1" },
    { x: 9, y: 0, frameCoordinate: "4x1" },
    { x: 10, y: 0, frameCoordinate: "4x1" },
    { x: 11, y: 0, frameCoordinate: null },
    { x: 0, y: 1, frameCoordinate: "4x1" },
    { x: 1, y: 1, frameCoordinate: "4x1" },
    { x: 2, y: 1, frameCoordinate: "4x1" },
    { x: 3, y: 1, frameCoordinate: "4x1" },
    { x: 4, y: 1, frameCoordinate: "4x1" },
    { x: 5, y: 1, frameCoordinate: "4x1" },
    { x: 6, y: 1, frameCoordinate: "4x1" },
    { x: 7, y: 1, frameCoordinate: "4x1" },
    { x: 8, y: 1, frameCoordinate: "4x1" },
    { x: 9, y: 1, frameCoordinate: "4x1" },
    { x: 10, y: 1, frameCoordinate: "4x1" },
    { x: 11, y: 1, frameCoordinate: "4x1" },
    { x: 0, y: 2, frameCoordinate: "4x1" },
    { x: 1, y: 2, frameCoordinate: "4x1" },
    { x: 2, y: 2, frameCoordinate: "4x1" },
    { x: 3, y: 2, frameCoordinate: "4x1" },
    { x: 4, y: 2, frameCoordinate: "4x1" },
    { x: 5, y: 2, frameCoordinate: "4x1" },
    { x: 6, y: 2, frameCoordinate: "4x1" },
    { x: 7, y: 2, frameCoordinate: "4x1" },
    { x: 8, y: 2, frameCoordinate: "4x1" },
    { x: 9, y: 2, frameCoordinate: "4x1" },
    { x: 10, y: 2, frameCoordinate: "4x1" },
    { x: 11, y: 2, frameCoordinate: "4x1" },
    { x: 0, y: 3, frameCoordinate: "4x1" },
    { x: 1, y: 3, frameCoordinate: "4x1" },
    { x: 2, y: 3, frameCoordinate: "4x1" },
    { x: 3, y: 3, frameCoordinate: "4x1" },
    { x: 4, y: 3, frameCoordinate: "4x1" },
    { x: 5, y: 3, frameCoordinate: "4x1" },
    { x: 6, y: 3, frameCoordinate: "4x1" },
    { x: 7, y: 3, frameCoordinate: "4x1" },
    { x: 8, y: 3, frameCoordinate: "4x1" },
    { x: 9, y: 3, frameCoordinate: "4x1" },
    { x: 10, y: 3, frameCoordinate: "4x1" },
    { x: 11, y: 3, frameCoordinate: "4x1" },
    { x: 0, y: 4, frameCoordinate: null },
    { x: 1, y: 4, frameCoordinate: "4x1" },
    { x: 2, y: 4, frameCoordinate: "4x1" },
    { x: 3, y: 4, frameCoordinate: "4x1" },
    { x: 4, y: 4, frameCoordinate: "4x1" },
    { x: 5, y: 4, frameCoordinate: "4x1" },
    { x: 6, y: 4, frameCoordinate: "4x1" },
    { x: 7, y: 4, frameCoordinate: "4x1" },
    { x: 8, y: 4, frameCoordinate: "4x1" },
    { x: 9, y: 4, frameCoordinate: "4x1" },
    { x: 10, y: 4, frameCoordinate: "4x1" },
    { x: 11, y: 4, frameCoordinate: "4x1" },
    { x: 0, y: 5, frameCoordinate: null },
    { x: 1, y: 5, frameCoordinate: "4x1" },
    { x: 2, y: 5, frameCoordinate: "4x1" },
    { x: 3, y: 5, frameCoordinate: "4x1" },
    { x: 4, y: 5, frameCoordinate: null },
    { x: 5, y: 5, frameCoordinate: null },
    { x: 6, y: 5, frameCoordinate: null },
    { x: 7, y: 5, frameCoordinate: "4x1" },
    { x: 8, y: 5, frameCoordinate: "4x1" },
    { x: 9, y: 5, frameCoordinate: "4x1" },
    { x: 10, y: 5, frameCoordinate: "4x1" },
    { x: 11, y: 5, frameCoordinate: "4x1" },
    { x: 0, y: 6, frameCoordinate: "4x1" },
    { x: 1, y: 6, frameCoordinate: "4x1" },
    { x: 2, y: 6, frameCoordinate: "4x1" },
    { x: 3, y: 6, frameCoordinate: "4x1" },
    { x: 4, y: 6, frameCoordinate: "4x1" },
    { x: 5, y: 6, frameCoordinate: null },
    { x: 6, y: 6, frameCoordinate: null },
    { x: 7, y: 6, frameCoordinate: "4x1" },
    { x: 8, y: 6, frameCoordinate: "4x1" },
    { x: 9, y: 6, frameCoordinate: "4x1" },
    { x: 10, y: 6, frameCoordinate: "4x1" },
    { x: 11, y: 6, frameCoordinate: "4x1" },
    { x: 0, y: 7, frameCoordinate: "4x1" },
    { x: 1, y: 7, frameCoordinate: "4x1" },
    { x: 2, y: 7, frameCoordinate: "4x1" },
    { x: 3, y: 7, frameCoordinate: "4x1" },
    { x: 4, y: 7, frameCoordinate: "4x1" },
    { x: 5, y: 7, frameCoordinate: "4x1" },
    { x: 6, y: 7, frameCoordinate: "4x1" },
    { x: 7, y: 7, frameCoordinate: "4x1" },
    { x: 8, y: 7, frameCoordinate: "4x1" },
    { x: 9, y: 7, frameCoordinate: "4x1" },
    { x: 10, y: 7, frameCoordinate: "4x1" },
    { x: 11, y: 7, frameCoordinate: "4x1" },
    { x: 0, y: 8, frameCoordinate: "4x1" },
    { x: 1, y: 8, frameCoordinate: "4x1" },
    { x: 2, y: 8, frameCoordinate: "4x1" },
    { x: 3, y: 8, frameCoordinate: "4x1" },
    { x: 4, y: 8, frameCoordinate: "4x1" },
    { x: 5, y: 8, frameCoordinate: "4x1" },
    { x: 6, y: 8, frameCoordinate: "4x1" },
    { x: 7, y: 8, frameCoordinate: "4x1" },
    { x: 8, y: 8, frameCoordinate: "4x1" },
    { x: 9, y: 8, frameCoordinate: "4x1" },
    { x: 10, y: 8, frameCoordinate: "4x1" },
    { x: 11, y: 8, frameCoordinate: "4x1" },
    { x: 0, y: 9, frameCoordinate: "4x1" },
    { x: 1, y: 9, frameCoordinate: "4x1" },
    { x: 2, y: 9, frameCoordinate: "4x1" },
    { x: 3, y: 9, frameCoordinate: "4x1" },
    { x: 4, y: 9, frameCoordinate: "4x1" },
    { x: 5, y: 9, frameCoordinate: "4x1" },
    { x: 6, y: 9, frameCoordinate: "4x1" },
    { x: 7, y: 9, frameCoordinate: "4x1" },
    { x: 8, y: 9, frameCoordinate: "4x1" },
    { x: 9, y: 9, frameCoordinate: "4x1" },
    { x: 10, y: 9, frameCoordinate: "4x1" },
    { x: 11, y: 9, frameCoordinate: "4x1" },
    { x: 0, y: 10, frameCoordinate: "4x1" },
    { x: 1, y: 10, frameCoordinate: "4x1" },
    { x: 2, y: 10, frameCoordinate: "4x1" },
    { x: 3, y: 10, frameCoordinate: "4x1" },
    { x: 4, y: 10, frameCoordinate: "4x1" },
    { x: 5, y: 10, frameCoordinate: "4x1" },
    { x: 6, y: 10, frameCoordinate: "4x1" },
    { x: 7, y: 10, frameCoordinate: "4x1" },
    { x: 8, y: 10, frameCoordinate: "4x1" },
    { x: 9, y: 10, frameCoordinate: "4x1" },
    { x: 10, y: 10, frameCoordinate: "4x1" },
    { x: 11, y: 10, frameCoordinate: "4x1" },
    { x: 0, y: 11, frameCoordinate: null },
    { x: 1, y: 11, frameCoordinate: "4x1" },
    { x: 2, y: 11, frameCoordinate: "4x1" },
    { x: 3, y: 11, frameCoordinate: "4x1" },
    { x: 4, y: 11, frameCoordinate: "4x1" },
    { x: 5, y: 11, frameCoordinate: "4x1" },
    { x: 6, y: 11, frameCoordinate: "4x1" },
    { x: 7, y: 11, frameCoordinate: "4x1" },
    { x: 8, y: 11, frameCoordinate: "4x1" },
    { x: 9, y: 11, frameCoordinate: "4x1" },
    { x: 10, y: 11, frameCoordinate: "4x1" },
    { x: 11, y: 11, frameCoordinate: null },
  ],
  placements: [
    { type: "HERO", x: 2, y: 1 },
    { type: "BOUND", x: 0, y: 1, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 2, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 3, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 6, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 7, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 8, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 9, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 10, direction: "LEFT" },
    { type: "BOUND", x: 1, y: 11, direction: "BOTTOM" },
    { type: "BOUND", x: 3, y: 11, direction: "BOTTOM" },
    { type: "BOUND", x: 2, y: 11, direction: "BOTTOM" },
    { type: "BOUND", x: 4, y: 11, direction: "BOTTOM" },
    { type: "BOUND", x: 5, y: 11, direction: "BOTTOM" },
    { type: "BOUND", x: 6, y: 11, direction: "BOTTOM" },
    { type: "BOUND", x: 7, y: 11, direction: "BOTTOM" },
    { type: "BOUND", x: 8, y: 11, direction: "BOTTOM" },
    { type: "BOUND", x: 9, y: 11, direction: "BOTTOM" },
    { type: "BOUND", x: 10, y: 11, direction: "BOTTOM" },
    { type: "BOUND", x: 11, y: 10, direction: "RIGHT" },
    { type: "BOUND", x: 11, y: 9, direction: "RIGHT" },
    { type: "BOUND", x: 11, y: 8, direction: "RIGHT" },
    { type: "BOUND", x: 11, y: 6, direction: "RIGHT" },
    { type: "BOUND", x: 11, y: 7, direction: "RIGHT" },
    { type: "BOUND", x: 11, y: 5, direction: "RIGHT" },
    { type: "BOUND", x: 11, y: 4, direction: "RIGHT" },
    { type: "BOUND", x: 11, y: 3, direction: "RIGHT" },
    { type: "BOUND", x: 11, y: 2, direction: "RIGHT" },
    { type: "BOUND", x: 11, y: 1, direction: "RIGHT" },
    { type: "BOUND", x: 10, y: 0, direction: "TOP" },
    { type: "BOUND", x: 8, y: 0, direction: "TOP" },
    { type: "BOUND", x: 9, y: 0, direction: "TOP" },
    { type: "BOUND", x: 7, y: 0, direction: "TOP" },
    { type: "BOUND", x: 6, y: 0, direction: "TOP" },
    { type: "BOUND", x: 5, y: 0, direction: "TOP" },
    { type: "BOUND", x: 3, y: 0, direction: "TOP" },
    { type: "BOUND", x: 4, y: 0, direction: "TOP" },
    { type: "BOUND", x: 2, y: 0, direction: "TOP" },
    { type: "BOUND", x: 1, y: 0, direction: "TOP" },
    { type: "BOUND", x: 4, y: 4, direction: "BOTTOM" },
    { type: "BOUND", x: 5, y: 4, direction: "BOTTOM" },
    { type: "BOUND", x: 6, y: 4, direction: "BOTTOM" },
    { type: "BOUND", x: 7, y: 4, direction: "LEFT" },
    { type: "BOUND", x: 7, y: 5, direction: "LEFT" },
    { type: "BOUND", x: 7, y: 6, direction: "LEFT" },
    { type: "BOUND", x: 7, y: 7, direction: "TOP" },
    { type: "BOUND", x: 6, y: 7, direction: "TOP" },
    { type: "BOUND", x: 5, y: 7, direction: "TOP" },
    { type: "BOUND", x: 4, y: 7, direction: "RIGHT" },
    { type: "BOUND", x: 4, y: 6, direction: "RIGHT" },
    { type: "BOUND", x: 3, y: 4, direction: "BOTTOM" },
    { type: "BOUND", x: 2, y: 4, direction: "BOTTOM" },
    { type: "BOUND", x: 1, y: 4, direction: "BOTTOM" },
    { type: "BOUND", x: 1, y: 5, direction: "TOP" },
    { type: "BOUND", x: 2, y: 5, direction: "TOP" },
    { type: "BOUND", x: 3, y: 5, direction: "TOP" },
    { type: "WALL", x: 3, y: 3 },
    { type: "WALL", x: 3, y: 2 },
    { type: "WALL", x: 5, y: 1 },
    { type: "WALL", x: 5, y: 2 },
    { type: "WALL", x: 7, y: 3 },
    { type: "WALL", x: 7, y: 2 },
    { type: "WALL", x: 8, y: 3 },
    { type: "WALL", x: 9, y: 4 },
    { type: "WALL", x: 9, y: 5 },
    { type: "ICE", x: 8, y: 6 },
    { type: "ICE", x: 9, y: 6 },
    { type: "ICE", x: 10, y: 6 },
    { type: "ICE", x: 10, y: 7 },
    { type: "ICE", x: 10, y: 7, corner: ICE_CORNERS.BOTTOM_RIGHT },
    { type: "ICE", x: 9, y: 7 },
    { type: "ICE", x: 8, y: 7, corner: ICE_CORNERS.BOTTOM_LEFT },
    { type: "WALL", x: 3, y: 7 },
    { type: "WALL", x: 1, y: 7 },
    { type: "GOAL", x: 2, y: 6 },
    { type: "LOCK", x: 2, y: 7, color: "GREEN" },
    { type: "WALL", x: 10, y: 2 },
    { type: "KEY", x: 10, y: 1, color: "GREEN" },
    { type: "SWITCH_DOOR", x: 9, y: 1, isRaised: true },
    { type: "SWITCH", x: 10, y: 10 },
    { type: "WALL", x: 6, y: 8 },
    { type: "WALL", x: 6, y: 9 },
    { type: "WALL", x: 9, y: 10 },
    { type: "WALL", x: 9, y: 9 },
    { type: "WALL", x: 8, y: 10 },
    { type: "ICE_PICKUP", x: 8, y: 4 },
    { type: "LOCK", x: 10, y: 9, color: "BLUE" },
    { type: "KEY", x: 8, y: 5, color: "BLUE" },
    { type: "THIEF", x: 4, y: 9 },
    { type: "FLOUR", x: 3, y: 9 },
    { type: "THIEF", x: 2, y: 9 },
    { type: "FLYING_ENEMY", x: 1, y: 10 },
    { type: "FLYING_ENEMY", x: 5, y: 8 },
  ],
};
export default level1;
