import { Direction } from "@/constants/helpers";

const level3 = {
  theme: "GRAY",
  tilesHeight: 12,
  tilesWidth: 12,
  tiles: [
    { x: 0, y: 0, frameCoordinate: null },
    { x: 1, y: 0, frameCoordinate: null },
    { x: 2, y: 0, frameCoordinate: "13x1" },
    { x: 3, y: 0, frameCoordinate: "13x1" },
    { x: 4, y: 0, frameCoordinate: "13x1" },
    { x: 5, y: 0, frameCoordinate: "13x1" },
    { x: 6, y: 0, frameCoordinate: "13x1" },
    { x: 7, y: 0, frameCoordinate: "13x1" },
    { x: 8, y: 0, frameCoordinate: "13x1" },
    { x: 9, y: 0, frameCoordinate: "13x1" },
    { x: 10, y: 0, frameCoordinate: "13x1" },
    { x: 11, y: 0, frameCoordinate: "13x1" },
    { x: 0, y: 1, frameCoordinate: null },
    { x: 1, y: 1, frameCoordinate: null },
    { x: 2, y: 1, frameCoordinate: "13x1" },
    { x: 3, y: 1, frameCoordinate: "13x1" },
    { x: 4, y: 1, frameCoordinate: "13x1" },
    { x: 5, y: 1, frameCoordinate: "13x1" },
    { x: 6, y: 1, frameCoordinate: "13x1" },
    { x: 7, y: 1, frameCoordinate: "13x1" },
    { x: 8, y: 1, frameCoordinate: "13x1" },
    { x: 9, y: 1, frameCoordinate: "13x1" },
    { x: 10, y: 1, frameCoordinate: "13x1" },
    { x: 11, y: 1, frameCoordinate: "13x1" },
    { x: 0, y: 2, frameCoordinate: null },
    { x: 1, y: 2, frameCoordinate: null },
    { x: 2, y: 2, frameCoordinate: "13x1" },
    { x: 3, y: 2, frameCoordinate: "13x1" },
    { x: 4, y: 2, frameCoordinate: "13x1" },
    { x: 5, y: 2, frameCoordinate: "13x1" },
    { x: 6, y: 2, frameCoordinate: "13x1" },
    { x: 7, y: 2, frameCoordinate: "13x1" },
    { x: 8, y: 2, frameCoordinate: "13x1" },
    { x: 9, y: 2, frameCoordinate: "13x1" },
    { x: 10, y: 2, frameCoordinate: "13x1" },
    { x: 11, y: 2, frameCoordinate: "13x1" },
    { x: 0, y: 3, frameCoordinate: null },
    { x: 1, y: 3, frameCoordinate: null },
    { x: 2, y: 3, frameCoordinate: "13x1" },
    { x: 3, y: 3, frameCoordinate: "13x1" },
    { x: 4, y: 3, frameCoordinate: "13x1" },
    { x: 5, y: 3, frameCoordinate: "13x1" },
    { x: 6, y: 3, frameCoordinate: "13x1" },
    { x: 7, y: 3, frameCoordinate: "13x1" },
    { x: 8, y: 3, frameCoordinate: "13x1" },
    { x: 9, y: 3, frameCoordinate: "13x1" },
    { x: 10, y: 3, frameCoordinate: "13x1" },
    { x: 11, y: 3, frameCoordinate: "13x1" },
    { x: 0, y: 4, frameCoordinate: null },
    { x: 1, y: 4, frameCoordinate: null },
    { x: 2, y: 4, frameCoordinate: "13x1" },
    { x: 3, y: 4, frameCoordinate: "13x1" },
    { x: 4, y: 4, frameCoordinate: "13x1" },
    { x: 5, y: 4, frameCoordinate: "13x1" },
    { x: 6, y: 4, frameCoordinate: "13x1" },
    { x: 7, y: 4, frameCoordinate: "13x1" },
    { x: 8, y: 4, frameCoordinate: "13x1" },
    { x: 9, y: 4, frameCoordinate: "13x1" },
    { x: 10, y: 4, frameCoordinate: "13x1" },
    { x: 11, y: 4, frameCoordinate: "13x1" },
    { x: 0, y: 5, frameCoordinate: null },
    { x: 1, y: 5, frameCoordinate: null },
    { x: 2, y: 5, frameCoordinate: "13x1" },
    { x: 3, y: 5, frameCoordinate: "13x1" },
    { x: 4, y: 5, frameCoordinate: "13x1" },
    { x: 5, y: 5, frameCoordinate: "13x1" },
    { x: 6, y: 5, frameCoordinate: "13x1" },
    { x: 7, y: 5, frameCoordinate: "13x1" },
    { x: 8, y: 5, frameCoordinate: "13x1" },
    { x: 9, y: 5, frameCoordinate: "13x1" },
    { x: 10, y: 5, frameCoordinate: "13x1" },
    { x: 11, y: 5, frameCoordinate: "13x1" },
    { x: 0, y: 6, frameCoordinate: null },
    { x: 1, y: 6, frameCoordinate: null },
    { x: 2, y: 6, frameCoordinate: "13x1" },
    { x: 3, y: 6, frameCoordinate: "13x1" },
    { x: 4, y: 6, frameCoordinate: "13x1" },
    { x: 5, y: 6, frameCoordinate: "13x1" },
    { x: 6, y: 6, frameCoordinate: "13x1" },
    { x: 7, y: 6, frameCoordinate: "13x1" },
    { x: 8, y: 6, frameCoordinate: "13x1" },
    { x: 9, y: 6, frameCoordinate: "13x1" },
    { x: 10, y: 6, frameCoordinate: "13x1" },
    { x: 11, y: 6, frameCoordinate: "13x1" },
    { x: 0, y: 7, frameCoordinate: null },
    { x: 1, y: 7, frameCoordinate: null },
    { x: 2, y: 7, frameCoordinate: "13x1" },
    { x: 3, y: 7, frameCoordinate: "13x1" },
    { x: 4, y: 7, frameCoordinate: "13x1" },
    { x: 5, y: 7, frameCoordinate: "13x1" },
    { x: 6, y: 7, frameCoordinate: "13x1" },
    { x: 7, y: 7, frameCoordinate: "13x1" },
    { x: 8, y: 7, frameCoordinate: "13x1" },
    { x: 9, y: 7, frameCoordinate: "13x1" },
    { x: 10, y: 7, frameCoordinate: "13x1" },
    { x: 11, y: 7, frameCoordinate: "13x1" },
    { x: 0, y: 8, frameCoordinate: null },
    { x: 1, y: 8, frameCoordinate: null },
    { x: 2, y: 8, frameCoordinate: "13x1" },
    { x: 3, y: 8, frameCoordinate: "13x1" },
    { x: 4, y: 8, frameCoordinate: "13x1" },
    { x: 5, y: 8, frameCoordinate: "13x1" },
    { x: 6, y: 8, frameCoordinate: "13x1" },
    { x: 7, y: 8, frameCoordinate: "13x1" },
    { x: 8, y: 8, frameCoordinate: "13x1" },
    { x: 9, y: 8, frameCoordinate: "13x1" },
    { x: 10, y: 8, frameCoordinate: "13x1" },
    { x: 11, y: 8, frameCoordinate: "13x1" },
    { x: 0, y: 9, frameCoordinate: null },
    { x: 1, y: 9, frameCoordinate: null },
    { x: 2, y: 9, frameCoordinate: "13x1" },
    { x: 3, y: 9, frameCoordinate: "13x1" },
    { x: 4, y: 9, frameCoordinate: "13x1" },
    { x: 5, y: 9, frameCoordinate: "13x1" },
    { x: 6, y: 9, frameCoordinate: "13x1" },
    { x: 7, y: 9, frameCoordinate: "13x1" },
    { x: 8, y: 9, frameCoordinate: "13x1" },
    { x: 9, y: 9, frameCoordinate: "13x1" },
    { x: 10, y: 9, frameCoordinate: "13x1" },
    { x: 11, y: 9, frameCoordinate: "13x1" },
    { x: 0, y: 10, frameCoordinate: null },
    { x: 1, y: 10, frameCoordinate: null },
    { x: 2, y: 10, frameCoordinate: "13x1" },
    { x: 3, y: 10, frameCoordinate: "13x1" },
    { x: 4, y: 10, frameCoordinate: "13x1" },
    { x: 5, y: 10, frameCoordinate: "13x1" },
    { x: 6, y: 10, frameCoordinate: "13x1" },
    { x: 7, y: 10, frameCoordinate: "13x1" },
    { x: 8, y: 10, frameCoordinate: "13x1" },
    { x: 9, y: 10, frameCoordinate: "13x1" },
    { x: 10, y: 10, frameCoordinate: "13x1" },
    { x: 11, y: 10, frameCoordinate: "13x1" },
    { x: 0, y: 11, frameCoordinate: null },
    { x: 1, y: 11, frameCoordinate: null },
    { x: 2, y: 11, frameCoordinate: null },
    { x: 3, y: 11, frameCoordinate: "13x1" },
    { x: 4, y: 11, frameCoordinate: "13x1" },
    { x: 5, y: 11, frameCoordinate: "13x1" },
    { x: 6, y: 11, frameCoordinate: "13x1" },
    { x: 7, y: 11, frameCoordinate: "13x1" },
    { x: 8, y: 11, frameCoordinate: "13x1" },
    { x: 9, y: 11, frameCoordinate: "13x1" },
    { x: 10, y: 11, frameCoordinate: "13x1" },
    { x: 11, y: 11, frameCoordinate: "13x1" },
  ],
  placements: [
    { type: "HERO", x: 10, y: 10 },
    { type: "KEY", x: 2, y: 2, color: "GREEN" },
    { type: "WALL", x: 4, y: 2 },
    { type: "WALL", x: 4, y: 3 },
    { type: "WALL", x: 4, y: 5 },
    { type: "WALL", x: 4, y: 6 },
    { type: "WALL", x: 6, y: 1 },
    { type: "WALL", x: 7, y: 1 },
    { type: "WALL", x: 6, y: 4 },
    { type: "WALL", x: 6, y: 4 },
    { type: "LOCK", x: 6, y: 5, color: "BLUE" },
    { type: "WALL", x: 6, y: 6 },
    { type: "WALL", x: 7, y: 6 },
    { type: "WALL", x: 7, y: 4 },
    { type: "WALL", x: 8, y: 4 },
    { type: "WALL", x: 9, y: 4 },
    { type: "WALL", x: 9, y: 4 },
    { type: "WALL", x: 9, y: 2 },
    { type: "WALL", x: 9, y: 3 },
    { type: "WALL", x: 9, y: 1 },
    { type: "WALL", x: 9, y: 5 },
    { type: "LOCK", x: 9, y: 6, color: "GREEN" },
    { type: "WALL", x: 6, y: 3 },
    { type: "FLOUR", x: 8, y: 1 },
    { type: "FLOUR", x: 5, y: 6 },
    { type: "WALL", x: 6, y: 7 },
    { type: "KEY", x: 8, y: 3, color: "BLUE" },
    { type: "GOAL", x: 11, y: 2 },
    { type: "BOUND", x: 3, y: 0, direction: "TOP" },
    { type: "BOUND", x: 2, y: 1, direction: "LEFT" },
    { type: "BOUND", x: 2, y: 0, direction: "LEFT" },
    { type: "BOUND", x: 2, y: 2, direction: "LEFT" },
    { type: "BOUND", x: 2, y: 3, direction: "LEFT" },
    { type: "BOUND", x: 2, y: 4, direction: "LEFT" },
    { type: "BOUND", x: 2, y: 5, direction: "LEFT" },
    { type: "BOUND", x: 2, y: 6, direction: "LEFT" },
    { type: "BOUND", x: 2, y: 7, direction: "LEFT" },
    { type: "BOUND", x: 4, y: 0, direction: "TOP" },
    { type: "BOUND", x: 5, y: 0, direction: "TOP" },
    { type: "BOUND", x: 6, y: 0, direction: "TOP" },
    { type: "BOUND", x: 7, y: 0, direction: "TOP" },
    { type: "BOUND", x: 8, y: 0, direction: "TOP" },
    { type: "BOUND", x: 9, y: 0, direction: "TOP" },
    { type: "BOUND", x: 10, y: 0, direction: "TOP" },
    { type: "BOUND", x: 11, y: 0, direction: "TOP" },
    { type: "WALL", x: 11, y: 1 },
    { type: "WALL", x: 11, y: 3 },
    { type: "WALL", x: 11, y: 4 },
    { type: "WALL", x: 11, y: 5 },
    { type: "WALL", x: 11, y: 6 },
    { type: "WALL", x: 4, y: 7 },
    { type: "WALL", x: 4, y: 8 },
    { type: "WALL", x: 5, y: 8 },
    { type: "WALL", x: 6, y: 8 },
    { type: "WALL", x: 7, y: 8 },
    { type: "WALL", x: 8, y: 8 },
    { type: "WALL", x: 9, y: 8 },
    { type: "WALL", x: 10, y: 8 },
    { type: "WALL", x: 11, y: 8 },
    { type: "WALL", x: 11, y: 7 },
    { type: "WALL", x: 11, y: 9 },
    { type: "WALL", x: 11, y: 10 },

    { type: "BOUND", x: 11, y: 11, direction: "BOTTOM" },
    { type: "BOUND", x: 10, y: 11, direction: "BOTTOM" },
    { type: "BOUND", x: 9, y: 11, direction: "BOTTOM" },
    { type: "BOUND", x: 8, y: 11, direction: "BOTTOM" },
    { type: "BOUND", x: 7, y: 11, direction: "BOTTOM" },
    { type: "BOUND", x: 6, y: 11, direction: "BOTTOM" },
    { type: "BOUND", x: 5, y: 11, direction: "BOTTOM" },
    { type: "BOUND", x: 4, y: 11, direction: "BOTTOM" },
    { type: "BOUND", x: 3, y: 11, direction: "BOTTOM" },
    { type: "BOUND", x: 2, y: 8, direction: "LEFT" },
    { type: "BOUND", x: 2, y: 9, direction: "LEFT" },
    { type: "BOUND", x: 2, y: 10, direction: "LEFT" },
    { type: "WALL", x: 9, y: 10 },
    { type: "WALL", x: 7, y: 9 },
    { type: "WALL", x: 5, y: 10 },
    { type: "WALL", x: 4, y: 1 },
    { type: "WALL", x: 9, y: 7 },
    { type: "LOCK", x: 4, y: 4, color: "GREEN" },
    { type: "KEY", x: 3, y: 4, color: "GREEN" },
    { type: "GROUND_ENEMY", x: 3, y: 1, initialDirection: Direction.Top },
  ],
};

export default level3;
