import { Direction } from "@/constants/helpers";

const level2 = {
  theme: "GREEN",
  tilesHeight: 11,
  tilesWidth: 20,
  tiles: [
    { x: 0, y: 0, frameCoordinate: null },
    { x: 1, y: 0, frameCoordinate: null },
    { x: 2, y: 0, frameCoordinate: "7x1" },
    { x: 3, y: 0, frameCoordinate: "7x1" },
    { x: 4, y: 0, frameCoordinate: "7x1" },
    { x: 5, y: 0, frameCoordinate: "7x1" },
    { x: 6, y: 0, frameCoordinate: "7x1" },
    { x: 7, y: 0, frameCoordinate: "7x1" },
    { x: 8, y: 0, frameCoordinate: "7x1" },
    { x: 9, y: 0, frameCoordinate: "7x1" },
    { x: 10, y: 0, frameCoordinate: "7x1" },
    { x: 11, y: 0, frameCoordinate: "7x1" },
    { x: 12, y: 0, frameCoordinate: "7x1" },
    { x: 13, y: 0, frameCoordinate: "7x1" },
    { x: 14, y: 0, frameCoordinate: "7x1" },
    { x: 15, y: 0, frameCoordinate: "7x1" },
    { x: 16, y: 0, frameCoordinate: "7x1" },
    { x: 17, y: 0, frameCoordinate: "7x1" },
    { x: 18, y: 0, frameCoordinate: "7x1" },
    { x: 19, y: 0, frameCoordinate: null },
    { x: 0, y: 1, frameCoordinate: "7x1" },
    { x: 1, y: 1, frameCoordinate: "7x1" },
    { x: 2, y: 1, frameCoordinate: "7x1" },
    { x: 3, y: 1, frameCoordinate: "7x1" },
    { x: 4, y: 1, frameCoordinate: "7x1" },
    { x: 5, y: 1, frameCoordinate: "7x1" },
    { x: 6, y: 1, frameCoordinate: "7x1" },
    { x: 7, y: 1, frameCoordinate: "7x1" },
    { x: 8, y: 1, frameCoordinate: "7x1" },
    { x: 9, y: 1, frameCoordinate: "7x1" },
    { x: 10, y: 1, frameCoordinate: "7x1" },
    { x: 11, y: 1, frameCoordinate: "7x1" },
    { x: 12, y: 1, frameCoordinate: "7x1" },
    { x: 13, y: 1, frameCoordinate: "7x1" },
    { x: 14, y: 1, frameCoordinate: "7x1" },
    { x: 15, y: 1, frameCoordinate: "7x1" },
    { x: 16, y: 1, frameCoordinate: "7x1" },
    { x: 17, y: 1, frameCoordinate: "7x1" },
    { x: 18, y: 1, frameCoordinate: "7x1" },
    { x: 19, y: 1, frameCoordinate: "7x1" },
    { x: 0, y: 2, frameCoordinate: "7x1" },
    { x: 1, y: 2, frameCoordinate: "7x1" },
    { x: 2, y: 2, frameCoordinate: "7x1" },
    { x: 3, y: 2, frameCoordinate: "7x1" },
    { x: 4, y: 2, frameCoordinate: "7x1" },
    { x: 5, y: 2, frameCoordinate: "7x1" },
    { x: 6, y: 2, frameCoordinate: "7x1" },
    { x: 7, y: 2, frameCoordinate: "7x1" },
    { x: 8, y: 2, frameCoordinate: "7x1" },
    { x: 9, y: 2, frameCoordinate: "7x1" },
    { x: 10, y: 2, frameCoordinate: "7x1" },
    { x: 11, y: 2, frameCoordinate: "7x1" },
    { x: 12, y: 2, frameCoordinate: "7x1" },
    { x: 13, y: 2, frameCoordinate: "7x1" },
    { x: 14, y: 2, frameCoordinate: "7x1" },
    { x: 15, y: 2, frameCoordinate: "7x1" },
    { x: 16, y: 2, frameCoordinate: "7x1" },
    { x: 17, y: 2, frameCoordinate: "7x1" },
    { x: 18, y: 2, frameCoordinate: "7x1" },
    { x: 19, y: 2, frameCoordinate: "7x1" },
    { x: 0, y: 3, frameCoordinate: "7x1" },
    { x: 1, y: 3, frameCoordinate: "7x1" },
    { x: 2, y: 3, frameCoordinate: "7x1" },
    { x: 3, y: 3, frameCoordinate: "7x1" },
    { x: 4, y: 3, frameCoordinate: "7x1" },
    { x: 5, y: 3, frameCoordinate: "7x1" },
    { x: 6, y: 3, frameCoordinate: "7x1" },
    { x: 7, y: 3, frameCoordinate: "7x1" },
    { x: 8, y: 3, frameCoordinate: "7x1" },
    { x: 9, y: 3, frameCoordinate: "7x1" },
    { x: 10, y: 3, frameCoordinate: "7x1" },
    { x: 11, y: 3, frameCoordinate: "7x1" },
    { x: 12, y: 3, frameCoordinate: "7x1" },
    { x: 13, y: 3, frameCoordinate: "7x1" },
    { x: 14, y: 3, frameCoordinate: "7x1" },
    { x: 15, y: 3, frameCoordinate: "7x1" },
    { x: 16, y: 3, frameCoordinate: "7x1" },
    { x: 17, y: 3, frameCoordinate: "7x1" },
    { x: 18, y: 3, frameCoordinate: "7x1" },
    { x: 19, y: 3, frameCoordinate: null },
    { x: 0, y: 4, frameCoordinate: "7x1" },
    { x: 1, y: 4, frameCoordinate: "7x1" },
    { x: 2, y: 4, frameCoordinate: "7x1" },
    { x: 3, y: 4, frameCoordinate: "7x1" },
    { x: 4, y: 4, frameCoordinate: "7x1" },
    { x: 5, y: 4, frameCoordinate: "7x1" },
    { x: 6, y: 4, frameCoordinate: "7x1" },
    { x: 7, y: 4, frameCoordinate: "7x1" },
    { x: 8, y: 4, frameCoordinate: "7x1" },
    { x: 9, y: 4, frameCoordinate: "7x1" },
    { x: 10, y: 4, frameCoordinate: "7x1" },
    { x: 11, y: 4, frameCoordinate: "7x1" },
    { x: 12, y: 4, frameCoordinate: null },
    { x: 13, y: 4, frameCoordinate: null },
    { x: 14, y: 4, frameCoordinate: null },
    { x: 15, y: 4, frameCoordinate: null },
    { x: 16, y: 4, frameCoordinate: "7x1" },
    { x: 17, y: 4, frameCoordinate: "7x1" },
    { x: 18, y: 4, frameCoordinate: "7x1" },
    { x: 19, y: 4, frameCoordinate: "7x1" },
    { x: 0, y: 5, frameCoordinate: "7x1" },
    { x: 1, y: 5, frameCoordinate: "7x1" },
    { x: 2, y: 5, frameCoordinate: "7x1" },
    { x: 3, y: 5, frameCoordinate: "7x1" },
    { x: 4, y: 5, frameCoordinate: null },
    { x: 5, y: 5, frameCoordinate: null },
    { x: 6, y: 5, frameCoordinate: null },
    { x: 7, y: 5, frameCoordinate: null },
    { x: 9, y: 5, frameCoordinate: "7x1" },
    { x: 10, y: 5, frameCoordinate: "7x1" },
    { x: 11, y: 5, frameCoordinate: "7x1" },
    { x: 12, y: 5, frameCoordinate: null },
    { x: 13, y: 5, frameCoordinate: null },
    { x: 14, y: 5, frameCoordinate: null },
    { x: 15, y: 5, frameCoordinate: null },
    { x: 16, y: 5, frameCoordinate: "7x1" },
    { x: 17, y: 5, frameCoordinate: "7x1" },
    { x: 18, y: 5, frameCoordinate: "7x1" },
    { x: 19, y: 5, frameCoordinate: "7x1" },
    { x: 0, y: 6, frameCoordinate: "7x1" },
    { x: 1, y: 6, frameCoordinate: "7x1" },
    { x: 2, y: 6, frameCoordinate: "7x1" },
    { x: 3, y: 6, frameCoordinate: "7x1" },
    { x: 4, y: 6, frameCoordinate: "7x1" },
    { x: 5, y: 6, frameCoordinate: "7x1" },
    { x: 6, y: 6, frameCoordinate: "7x1" },
    { x: 7, y: 6, frameCoordinate: "7x1" },
    { x: 8, y: 6, frameCoordinate: "7x1" },
    { x: 9, y: 6, frameCoordinate: "7x1" },
    { x: 10, y: 6, frameCoordinate: "7x1" },
    { x: 11, y: 6, frameCoordinate: "7x1" },
    { x: 12, y: 6, frameCoordinate: null },
    { x: 13, y: 6, frameCoordinate: null },
    { x: 14, y: 6, frameCoordinate: null },
    { x: 15, y: 6, frameCoordinate: null },
    { x: 16, y: 6, frameCoordinate: "7x1" },
    { x: 17, y: 6, frameCoordinate: "7x1" },
    { x: 18, y: 6, frameCoordinate: "7x1" },
    { x: 19, y: 6, frameCoordinate: "7x1" },
    { x: 0, y: 7, frameCoordinate: "7x1" },
    { x: 1, y: 7, frameCoordinate: "7x1" },
    { x: 2, y: 7, frameCoordinate: "7x1" },
    { x: 3, y: 7, frameCoordinate: "7x1" },
    { x: 4, y: 7, frameCoordinate: "7x1" },
    { x: 5, y: 7, frameCoordinate: "7x1" },
    { x: 6, y: 7, frameCoordinate: "7x1" },
    { x: 7, y: 7, frameCoordinate: "7x1" },
    { x: 8, y: 7, frameCoordinate: "7x1" },
    { x: 9, y: 7, frameCoordinate: "7x1" },
    { x: 10, y: 7, frameCoordinate: "7x1" },
    { x: 11, y: 7, frameCoordinate: "7x1" },
    { x: 12, y: 7, frameCoordinate: null },
    { x: 13, y: 7, frameCoordinate: null },
    { x: 14, y: 7, frameCoordinate: null },
    { x: 15, y: 7, frameCoordinate: null },
    { x: 16, y: 7, frameCoordinate: "7x1" },
    { x: 17, y: 7, frameCoordinate: "7x1" },
    { x: 18, y: 7, frameCoordinate: "7x1" },
    { x: 19, y: 7, frameCoordinate: "7x1" },
    { x: 0, y: 8, frameCoordinate: "7x1" },
    { x: 1, y: 8, frameCoordinate: "7x1" },
    { x: 2, y: 8, frameCoordinate: "7x1" },
    { x: 3, y: 8, frameCoordinate: "7x1" },
    { x: 4, y: 8, frameCoordinate: "7x1" },
    { x: 5, y: 8, frameCoordinate: "7x1" },
    { x: 6, y: 8, frameCoordinate: "7x1" },
    { x: 7, y: 8, frameCoordinate: "7x1" },
    { x: 8, y: 8, frameCoordinate: "7x1" },
    { x: 9, y: 8, frameCoordinate: "7x1" },
    { x: 10, y: 8, frameCoordinate: "7x1" },
    { x: 11, y: 8, frameCoordinate: "7x1" },
    { x: 12, y: 8, frameCoordinate: null },
    { x: 13, y: 8, frameCoordinate: null },
    { x: 14, y: 8, frameCoordinate: null },
    { x: 15, y: 8, frameCoordinate: null },
    { x: 8, y: 5, frameCoordinate: "null" },

    { x: 16, y: 8, frameCoordinate: "7x1" },
    { x: 17, y: 8, frameCoordinate: "7x1" },
    { x: 18, y: 8, frameCoordinate: "7x1" },
    { x: 19, y: 8, frameCoordinate: "7x1" },
    { x: 0, y: 9, frameCoordinate: "7x1" },
    { x: 1, y: 9, frameCoordinate: "7x1" },
    { x: 2, y: 9, frameCoordinate: "7x1" },
    { x: 3, y: 9, frameCoordinate: "7x1" },
    { x: 4, y: 9, frameCoordinate: "7x1" },
    { x: 5, y: 9, frameCoordinate: "7x1" },
    { x: 6, y: 9, frameCoordinate: "7x1" },
    { x: 7, y: 9, frameCoordinate: "7x1" },
    { x: 8, y: 9, frameCoordinate: "7x1" },
    { x: 9, y: 9, frameCoordinate: "7x1" },
    { x: 10, y: 9, frameCoordinate: "7x1" },
    { x: 11, y: 9, frameCoordinate: "7x1" },
    { x: 12, y: 9, frameCoordinate: null },
    { x: 13, y: 9, frameCoordinate: null },
    { x: 14, y: 9, frameCoordinate: null },
    { x: 15, y: 9, frameCoordinate: null },
    { x: 16, y: 9, frameCoordinate: "7x1" },
    { x: 17, y: 9, frameCoordinate: "7x1" },
    { x: 18, y: 9, frameCoordinate: "7x1" },
    { x: 19, y: 9, frameCoordinate: "7x1" },
    { x: 0, y: 10, frameCoordinate: null },
    { x: 1, y: 10, frameCoordinate: "7x1" },
    { x: 2, y: 10, frameCoordinate: "7x1" },
    { x: 3, y: 10, frameCoordinate: "7x1" },
    { x: 4, y: 10, frameCoordinate: "7x1" },
    { x: 5, y: 10, frameCoordinate: "7x1" },
    { x: 6, y: 10, frameCoordinate: "7x1" },
    { x: 7, y: 10, frameCoordinate: "7x1" },
    { x: 8, y: 10, frameCoordinate: "7x1" },
    { x: 9, y: 10, frameCoordinate: "7x1" },
    { x: 10, y: 10, frameCoordinate: "7x1" },
    { x: 11, y: 10, frameCoordinate: null },
    { x: 12, y: 10, frameCoordinate: null },
    { x: 13, y: 10, frameCoordinate: null },
    { x: 14, y: 10, frameCoordinate: null },
    { x: 15, y: 10, frameCoordinate: null },
    { x: 16, y: 10, frameCoordinate: null },
    { x: 17, y: 10, frameCoordinate: "7x1" },
    { x: 18, y: 10, frameCoordinate: "7x1" },
    { x: 19, y: 10, frameCoordinate: null },
  ],
  placements: [
    { type: "HERO", x: 2, y: 5 },
    { type: "WALL", x: 3, y: 1 },
    { type: "WALL", x: 4, y: 1 },
    { type: "WALL", x: 5, y: 1 },
    { type: "WALL", x: 6, y: 1 },
    { type: "WALL", x: 7, y: 1 },
    { type: "WALL", x: 8, y: 1 },
    { type: "WALL", x: 2, y: 9 },
    { type: "WALL", x: 3, y: 9 },
    { type: "WALL", x: 4, y: 9 },
    { type: "WALL", x: 5, y: 9 },
    { type: "WALL", x: 6, y: 9 },
    { type: "WALL", x: 7, y: 9 },
    { type: "WALL", x: 8, y: 9 },
    { type: "WALL", x: 2, y: 1 },
    { type: "FLOUR", x: 7, y: 3 },
    { type: "FLOUR", x: 7, y: 7 },
    { type: "FLOUR", x: 3, y: 7 },
    { type: "FLOUR", x: 3, y: 3 },
    { type: "BOUND", x: 8, y: 10, direction: "BOTTOM" },
    { type: "BOUND", x: 7, y: 10, direction: "BOTTOM" },
    { type: "BOUND", x: 5, y: 10, direction: "BOTTOM" },
    { type: "BOUND", x: 4, y: 10, direction: "BOTTOM" },
    { type: "BOUND", x: 6, y: 10, direction: "BOTTOM" },
    { type: "BOUND", x: 3, y: 10, direction: "BOTTOM" },
    { type: "BOUND", x: 2, y: 10, direction: "BOTTOM" },
    { type: "BOUND", x: 1, y: 10, direction: "BOTTOM" },
    { type: "BOUND", x: 0, y: 9, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 8, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 7, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 6, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 4, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 5, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 3, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 2, direction: "LEFT" },
    { type: "BOUND", x: 0, y: 1, direction: "LEFT" },
    { type: "BOUND", x: 2, y: 0, direction: "TOP" },
    { type: "BOUND", x: 4, y: 0, direction: "TOP" },
    { type: "BOUND", x: 5, y: 0, direction: "TOP" },
    { type: "BOUND", x: 3, y: 0, direction: "TOP" },
    { type: "BOUND", x: 6, y: 0, direction: "TOP" },
    { type: "BOUND", x: 7, y: 0, direction: "TOP" },
    { type: "BOUND", x: 8, y: 0, direction: "TOP" },
    { type: "BOUND", x: 9, y: 0, direction: "TOP" },
    { type: "BOUND", x: 1, y: 0, direction: "TOP" },
    { type: "BOUND", x: 9, y: 10, direction: "BOTTOM" },
    { type: "BOUND", x: 10, y: 10, direction: "BOTTOM" },
    { type: "BOUND", x: 17, y: 10, direction: "BOTTOM" },
    { type: "BOUND", x: 18, y: 10, direction: "BOTTOM" },
    { type: "BOUND", x: 11, y: 9, direction: "RIGHT" },
    { type: "BOUND", x: 11, y: 8, direction: "RIGHT" },
    { type: "BOUND", x: 11, y: 7, direction: "RIGHT" },
    { type: "BOUND", x: 11, y: 5, direction: "RIGHT" },
    { type: "BOUND", x: 11, y: 4, direction: "RIGHT" },
    { type: "BOUND", x: 11, y: 6, direction: "RIGHT" },
    { type: "BOUND", x: 19, y: 9, direction: "RIGHT" },
    { type: "BOUND", x: 19, y: 8, direction: "RIGHT" },
    { type: "BOUND", x: 19, y: 6, direction: "RIGHT" },
    { type: "BOUND", x: 19, y: 5, direction: "RIGHT" },
    { type: "BOUND", x: 19, y: 7, direction: "RIGHT" },
    { type: "BOUND", x: 19, y: 4, direction: "RIGHT" },
    { type: "BOUND", x: 19, y: 1, direction: "RIGHT" },
    { type: "BOUND", x: 19, y: 2, direction: "RIGHT" },
    { type: "BOUND", x: 8, y: 5, direction: "LEFT" },
    { type: "BOUND", x: 18, y: 0, direction: "TOP" },
    { type: "BOUND", x: 16, y: 0, direction: "TOP" },
    { type: "BOUND", x: 17, y: 0, direction: "TOP" },
    { type: "BOUND", x: 14, y: 0, direction: "TOP" },
    { type: "BOUND", x: 12, y: 0, direction: "TOP" },
    { type: "BOUND", x: 11, y: 0, direction: "TOP" },
    { type: "BOUND", x: 10, y: 0, direction: "TOP" },
    { type: "BOUND", x: 13, y: 0, direction: "TOP" },
    { type: "BOUND", x: 15, y: 0, direction: "TOP" },
    { type: "BOUND", x: 12, y: 3, direction: "BOTTOM" },
    { type: "BOUND", x: 13, y: 3, direction: "BOTTOM" },
    { type: "BOUND", x: 14, y: 3, direction: "BOTTOM" },
    { type: "BOUND", x: 15, y: 3, direction: "BOTTOM" },
    { type: "BOUND", x: 11, y: 3, direction: "RIGHT" },
    { type: "BOUND", x: 16, y: 3, direction: "LEFT" },
    { type: "BOUND", x: 16, y: 4, direction: "LEFT" },
    { type: "BOUND", x: 16, y: 5, direction: "LEFT" },
    { type: "BOUND", x: 16, y: 6, direction: "LEFT" },
    { type: "BOUND", x: 16, y: 7, direction: "LEFT" },
    { type: "BOUND", x: 16, y: 8, direction: "LEFT" },
    { type: "BOUND", x: 16, y: 9, direction: "LEFT" },
    { type: "WALL", x: 12, y: 2 },
    { type: "WALL", x: 15, y: 2 },
    { type: "BOUND", x: 19, y: 3, direction: "RIGHT" },
    { type: "WALL", x: 17, y: 3 },
    { type: "WALL", x: 18, y: 5 },
    { type: "WALL", x: 17, y: 7 },
    { type: "GOAL", x: 17, y: 9 },
    { type: "SWITCH_DOOR", x: 18, y: 7 },
    { type: "SWITCH", x: 18, y: 1 },
    { type: "GROUND_ENEMY", x: 18, y: 4, initialDirection: Direction.Top },
    { type: "GROUND_ENEMY", x: 1, y: 1, initialDirection: Direction.Top },
    { type: "GROUND_ENEMY", x: 9, y: 1, initialDirection: Direction.Top },
    { type: "GROUND_ENEMY", x: 10, y: 1 },
    { type: "GROUND_ENEMY", x: 9, y: 2 },
    { type: "GROUND_ENEMY", x: 9, y: 3 },
    { type: "BOUND", x: 3, y: 4, direction: "BOTTOM" },
    { type: "BOUND", x: 4, y: 4, direction: "BOTTOM" },
    { type: "BOUND", x: 5, y: 4, direction: "BOTTOM" },
    { type: "BOUND", x: 6, y: 4, direction: "BOTTOM" },
    { type: "BOUND", x: 7, y: 4, direction: "BOTTOM" },
    { type: "BOUND", x: 7, y: 6, direction: "TOP" },
    { type: "BOUND", x: 6, y: 6, direction: "TOP" },
    { type: "BOUND", x: 5, y: 6, direction: "TOP" },
    { type: "BOUND", x: 4, y: 6, direction: "TOP" },
    { type: "BOUND", x: 8, y: 4, direction: "LEFT" },
    { type: "BOUND", x: 8, y: 6, direction: "LEFT" },
    { type: "BOUND", x: 3, y: 5, direction: "RIGHT" },
    { type: "BOUND", x: 3, y: 6, direction: "RIGHT" },
    { type: "GROUND_ENEMY", x: 9, y: 7 },
    { type: "GROUND_ENEMY", x: 9, y: 8 },
  ],
};

export default level2;
