const level7 = {
  theme: "GREEN",
  tilesHeight: 4,
  tilesWidth: 10,
  tiles: [
    { x: 0, y: 0, frameCoordinate: "7x1" },
    { x: 1, y: 0, frameCoordinate: "7x1" },
    { x: 2, y: 0, frameCoordinate: "7x1" },
    { x: 3, y: 0, frameCoordinate: "7x1" },
    { x: 4, y: 0, frameCoordinate: null },
    { x: 5, y: 0, frameCoordinate: "7x1" },
    { x: 6, y: 0, frameCoordinate: "7x1" },
    { x: 7, y: 0, frameCoordinate: "7x1" },
    { x: 8, y: 0, frameCoordinate: "7x1" },
    { x: 9, y: 0, frameCoordinate: "7x1" },
    { x: 0, y: 1, frameCoordinate: "7x1" },
    { x: 1, y: 1, frameCoordinate: "7x1" },
    { x: 2, y: 1, frameCoordinate: "7x1" },
    { x: 3, y: 1, frameCoordinate: "7x1" },
    { x: 4, y: 1, frameCoordinate: null },
    { x: 5, y: 1, frameCoordinate: "7x1" },
    { x: 6, y: 1, frameCoordinate: "7x1" },
    { x: 7, y: 1, frameCoordinate: "7x1" },
    { x: 8, y: 1, frameCoordinate: "7x1" },
    { x: 9, y: 1, frameCoordinate: "7x1" },
    { x: 0, y: 2, frameCoordinate: "7x1" },
    { x: 1, y: 2, frameCoordinate: "7x1" },
    { x: 2, y: 2, frameCoordinate: "7x1" },
    { x: 3, y: 2, frameCoordinate: "7x1" },
    { x: 4, y: 2, frameCoordinate: null },
    { x: 5, y: 2, frameCoordinate: "7x1" },
    { x: 6, y: 2, frameCoordinate: "7x1" },
    { x: 7, y: 2, frameCoordinate: "7x1" },
    { x: 8, y: 2, frameCoordinate: "7x1" },
    { x: 9, y: 2, frameCoordinate: "7x1" },
    { x: 0, y: 3, frameCoordinate: "7x1" },
    { x: 1, y: 3, frameCoordinate: "7x1" },
    { x: 2, y: 3, frameCoordinate: "7x1" },
    { x: 3, y: 3, frameCoordinate: "7x1" },
    { x: 4, y: 3, frameCoordinate: null },
    { x: 5, y: 3, frameCoordinate: "7x1" },
    { x: 6, y: 3, frameCoordinate: "7x1" },
    { x: 7, y: 3, frameCoordinate: "7x1" },
    { x: 8, y: 3, frameCoordinate: "7x1" },
    { x: 9, y: 3, frameCoordinate: "7x1" },
  ],
  placements: [
    { type: "HERO", x: 2, y: 1 },
    { type: "WALL", x: 0, y: 0 },
    { type: "WALL", x: 0, y: 1 },
    { type: "WALL", x: 0, y: 2 },
    { type: "WALL", x: 0, y: 3 },
    { type: "WALL", x: 9, y: 0 },
    { type: "WALL", x: 9, y: 2 },
    { type: "WALL", x: 9, y: 1 },
    { type: "WALL", x: 9, y: 3 },
    { type: "WALL", x: 1, y: 0 },
    { type: "WALL", x: 2, y: 0 },
    { type: "WALL", x: 3, y: 0 },
    { type: "WALL", x: 5, y: 0 },
    { type: "WALL", x: 6, y: 0 },
    { type: "WALL", x: 7, y: 0 },
    { type: "WALL", x: 8, y: 0 },
    { type: "WALL", x: 8, y: 3 },
    { type: "WALL", x: 7, y: 3 },
    { type: "WALL", x: 6, y: 3 },
    { type: "WALL", x: 5, y: 3 },
    { type: "WALL", x: 3, y: 3 },
    { type: "WALL", x: 2, y: 3 },
    { type: "WALL", x: 1, y: 3 },
    { type: "WALL", x: 3, y: 1 },
    { type: "WALL", x: 3, y: 2 },
    { type: "WALL", x: 5, y: 1 },
    { type: "TELEPORT", x: 1, y: 2 },
    { type: "TELEPORT", x: 6, y: 2 },
    { type: "GOAL", x: 8, y: 2, asPortal: true },
    { type: "WALL", x: 5, y: 2 },
    { type: "WALL", x: 7, y: 2 },
    { type: "SWITCH", x: 1, y: 1, isRaised: true },
    { type: "SWITCH_DOOR", x: 7, y: 1, isRaised: true },
  ],
};

export default level7;
